version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: job-forge-postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: jobforge
      POSTGRES_PASSWORD: jobforge123
      POSTGRES_DB: jobforge
    volumes:
      - jobforge_pgdata:/var/lib/postgresql/data

volumes:
  jobforge_pgdata:
