version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: job-forge-postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: jobforge
      POSTGRES_PASSWORD: jobforge123
      POSTGRES_DB: jobforge
    volumes:
      - jobforge_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: job-forge-redis
    ports: 
      - "6379:6379"

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  jobforge_pgdata:
